steps_dir: gherkin/tests/steps

rag:
  provider: openai          # openai | gigachat
  params:
    model: text-embedding-3-large  # gigachat: Embeddings

  steps:
    collection_name: bdd_steps
    top_k: 8

  docs:
    collection_name: project_docs
    path: docs
    top_k: 5
    chunk_size: 1000
    chunk_overlap: 200

docstring:
  supported_langs:
    - python
    - json
    - xml
    - sql
