rag:
  provider: openai
  params:
    model: text-embedding-3-large

  steps:
    collection_name: bdd_steps
    top_k: 8

  docs:
    collection_name: project_docs
    path: docs
    top_k: 5
    chunk_size: 1000
    chunk_overlap: 200

  few_shots:
    collection_name: few_shots
    top_k: 3
    index_path: src/configs/few_shots_index.json
    few_shots_dir: few_shots
    batch_size: 100

docstring:
  supported_langs:
    - python
    - json
    - xml
    - sql
